[theme]
base = "dark"
primaryColor = "#E8002D"
backgroundColor = "#15151E"
secondaryBackgroundColor = "#1e1e2e"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 50
